; NRF52840 Pro Micro + DXLR30 / E22-900M22S (SX1262) - 915 MHz
; Meshtastic firmware variant
[env:promicro_dxlr30]
extends = nrf52840_base
board = promicro_dxlr30
board_level = extra
build_flags = ${nrf52840_base.build_flags}
    -I variants/nrf52840/promicro_dxlr30
    -D PROMICRO_DXLR30
    -D RADIOLIB_EXCLUDE_SX128X=1
    -D RADIOLIB_EXCLUDE_SX127X=1
    -D RADIOLIB_EXCLUDE_LR11X0=1
    -D CONFIG_NFCT_PINS_AS_GPIOS
    -D MESHTASTIC_EXCLUDE_GPS=1
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/promicro_dxlr30>
