name: Build Custom Firmware

on:
  workflow_dispatch:
    inputs:
      pio_env:
        description: "PlatformIO env (e.g. promicro_dxlr30)"
        required: true
        default: promicro_dxlr30
      platform:
        description: "Platform: esp32/esp32s3/esp32c3/nrf52840/rp2040"
        required: true
        default: nrf52840

jobs:
  build:
    uses: ./.github/workflows/build_firmware.yml
    with:
      version: "custom"
      platform: ${{ inputs.platform }}
      pio_env: ${{ inputs.pio_env }}
